### ISSUE TITLE
Example: Todo App using Svelte

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase#215]
# Feature request

## Is your feature request related to a problem? Please describe.

New example use case

## Describe the solution you'd like

- Create a initial React app in `examples/todos-svelte` using Svelte.js
- Build a todo list app, using Supabase as the backend. Use the [Slack Clone](https://github.com/supabase/supabase/blob/master/examples/slack-clone/README.md) as an example.
- Should include logins + policies
- Add a one-click deploy using Vercel deploy button

## Additional context

- Ant has done an example [here](https://github.com/supabase/supabase/tree/master/examples/todo), which is a good baseline
- Keep it as simple as possible - for styling we can use Tailwind

**Comment by himynameisdave** [comment]
Has anyone picked this up yet? If not I'd love to take a stab at it!

**Comment by duncanhealy** [comment]
yes I've started!

**Comment by duncanhealy** [comment]
> Has anyone picked this up yet? If not I'd love to take a stab at it!

Hi Dave - still some bits to do happy to collaborate

 The login and the policy bit and adding the db relations 
- [ ] Multi user sql below with policy?
- [ ] correct the svelte to create a list if none already
- [ ] The ui to share a todo list to allow someone to complete items from the same list needs to be done too

thinking something like below will cover the db and policy

```sql
CREATE TABLE lists (
  uuid text,
  id bigserial PRIMARY KEY,
  inserted_at timestamp without time zone DEFAULT timezone('utc' :: text, now()) NOT NULL,
  updated_at timestamp without time zone DEFAULT timezone('utc' :: text, now()) NOT NULL
);
ALTER TABLE lists ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow logged-in full access" on lists FOR ALL USING ( auth.role() = 'authenticated' );
CREATE TABLE tasks (
  task_text text NOT NULL,
  complete boolean DEFAULT false,
  id bigserial PRIMARY KEY,
  user_id uuid REFERENCES public.users NOT NULL,
  list_id bigint REFERENCES lists NOT NULL,
  inserted_at timestamp without time zone DEFAULT timezone('utc' :: text, now()) NOT NULL,
  updated_at timestamp without time zone DEFAULT timezone('utc' :: text, now()) NOT NULL
);
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow logged-in read access" on tasks USING ( auth.role() = 'authenticated' );
CREATE POLICY "Allow individual insert access" on tasks FOR INSERT WITH CHECK ( auth.uid() = user_id );
CREATE POLICY "Allow individual update access" on tasks FOR UPDATE USING ( auth.uid() = user_id );
````

**Comment by kiwicopple** [comment]
@duncanhealy great schema - I can add this to the QuickStart templates on app.supabase.io, and then all the other examples can use it too.

I would like to modify these:

```
CREATE POLICY "Allow logged-in full access" on lists FOR ALL USING ( auth.role() = 'authenticated' );
CREATE POLICY "Allow logged-in read access" on tasks USING ( auth.role() = 'authenticated' );
```

Perhaps we can design this one so that each individual can see their own lists/todos, but others cannot? This way, the app is multi-tenant with privacy baked-in: a developer can spin up a single front-end for a lot of individuals to use, keeping their todo's private from everyone else.

**Comment by duncanhealy** [comment]
In the case where an person wants to share a todo list with their partner say we would need a userlists table
or better would be an array/json in the lists table
in firebase we would do /todos/:uid/  and check against auth.uid()

@kiwicopple  
- [ ] seperate pr if we are updating db/task_list_schema.sql? #223
i see talk about that in #209 makes sense to extend the vanilla auth to be used by react / svelte / vue / ng etc

so to do it we have a policy for this here would look like #224

My First impressions using supabase - super I like the nested query took a few goes, until I realised the Promise was not going to resolve itself give me values - await all supabase calls :)
